spring:
  config:
    activate:
      on-profile: dev
    import: database-dev-secrets.yml
  datasource:
    url: jdbc:postgresql://${jpa-connection.host}:${jpa-connection.port}/${jpa-connection.database}
    username: ${database.username}
    password: ${database.password}
    sql:
      init:
        mode: always
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: true
    open-in-view: off
