spring:
  config:
    activate:
      on-profile: default
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:ingatlan_centrum
    username: test_user
    password: test_password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
