spring:
  config:
    activate:
      on-profile: dev
    import: database-secrets.yml
  datasource:
    url: jdbc:mysql://${database.url}/ingatlan_centrum
    username: ${database.username}
    password: ${database.password}
    sql:
      init:
        mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: none
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: true
    open-in-view: off
